version: "2.1"
services:
  # The opentelemetry-collector batches and processes traces sent to it.
  opentelemetry-collector:
    image: otel/opentelemetry-collector-contrib
    ports:
      - "4317:4317"
    volumes:
      - ./otel/otel-grafana.yml:/etc/otel-collector-config.yml
    command: ["--config=/etc/otel-collector-config.yml"]

  rest-api:
    image: philipz/otel-logback:agent
    ports:
      - "8080:8080"
    depends_on:
      - opentelemetry-collector
    environment:
      - OTEL_INSTRUMENTATION_RUNTIME_METRICS_ENABLED=true
      - OTEL_INSTRUMENTATION_LOGBACK_APPENDER_ENABLED=true
      - JAVA_TOOL_OPTIONS=-javaagent:/otel-auto-instrumentation-java/javaagent.jar
      - OTEL_SERVICE_NAME=rest-api
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://opentelemetry-collector:4317
      - OTEL_PROPAGATORS=tracecontext,baggage,b3
      - OTEL_TRACES_SAMPLER=parentbased_traceidratio
      - OTEL_TRACES_SAMPLER_ARG=0.25
      - OTEL_LOGS_EXPORTER=otlp